//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyOnlineShoppingStore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Order
    {
        public int OrderId { get; set; }
        public Nullable<int> CartId { get; set; }
        public Nullable<int> OrderStatusId { get; set; }
    
        public virtual Tbl_Cart Tbl_Cart { get; set; }
        public virtual Tbl_OrderStatus Tbl_OrderStatus { get; set; }
    }
}
