//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyOnlineShoppingStore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ShippingDetails
    {
        public int ShippingId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Address { get; set; }
        public string District { get; set; }
        public Nullable<int> ZipCode { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<decimal> ShippingCharge { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual Tbl_User Tbl_User { get; set; }
    }
}
